### ISSUE TITLE
Support for llama3

### ISSUE THREAD

**Issue by PylotLight** [unclecode/groqopilot#2]
It looks like the models don't automatically update/pull latest so will need you to update these.

**Comment by ChaseKolozsy** [comment]
Yes, Please! I'm very excited about the possibility of using your vscode extension with llama3. That's like free gpt4 copilot!

**Comment by babycommando** [comment]
This!

**Comment by MemeFormer** [comment]
Came here for that reason too, from what people saying llama3 rocks.
I trust unclecode is already on it as we speak.

**Comment by PylotLight** [comment]
Created PR for it.
https://github.com/unclecode/groqopilot/pull/4

**Comment by unclecode** [comment]
Hey everyone, just added Llama3 and a few other things. @PylotLight, thanks for the support! By the time I saw your PR, I'd already updated the code base.

Please make sure to update your extension to version 0.0.5.

@MemeFormer You were right ;)

I close this issue, if you find any other one, welcome to create a new one.
