### ISSUE TITLE
CSS ui/ux request - decrease hover color on messages, change cursor style to "auto"

### ISSUE THREAD

**Issue by babycommando** [unclecode/groqopilot#3]
![image](https://github.com/unclecode/groqopilot/assets/71618056/e768224a-a8b4-4ef9-83f8-95600270a3c5)

Hello there, so I believe the usability of groqpilot would be cleaner if this hover color could be decreased or eliminated completely. Also we need to actually copy text from it so having a pointer cursor is not the best thing, better setting it to auto.

Project is looking very good, hope to see Llama3 on it as soon as possible.

**Comment by unclecode** [comment]
Totally agree, already resolved, please update to v0.0.05.
