### ISSUE TITLE
Error: API key not set. 

### ISSUE THREAD

**Issue by MW-study** [unclecode/groqopilot#6]
Groqopilot v0.0.5
VSCode 1.88.1

- Installed from VSCode Marketplace
- Set API Key in extension settings
- Checked settings.json (key is set)
- Tried on Windows and MX-Linux
- did several app restarts

Get the following error:
"API key not set. Please configure the API key in the settings."

### Runtime Status
**Activation**
Activated by onView:groqopilotView event: 1ms

**Uncaught Errors (1)**
 Cannot read properties of undefined (reading 'value')

**Comment by rahulmanuwas** [comment]
"groqopilot.apiKey": "gsk_****u" - this is the issue on Mac, it's invalid JSON.

**Comment by MW-study** [comment]
It doesn't seem to be invalid to me, do mind elaborating?

I checked here. Seems fine.
https://jsonlint.com/
JSON Online Validator and Formatter - JSON Lint<https://jsonlint.com/>
JSONLint is the free online validator, json formatter, and json beautifier tool for JSON, a lightweight data-interchange format. You can format json, validate json, with a quick and easy copy+paste.
jsonlint.com

________________________________

**Comment by unclecode** [comment]
@MW-study Working on it, I will fix it and release the new version

**Comment by unclecode** [comment]
Issue has been resolved. If nothing on this, I will close this issue/

**Comment by Ginson** [comment]
> Issue has been resolved. If nothing on this, I will close this issue/

Thanks a lot, it is working.
